#QUEUES:
#    KAFKA:
#        HOST: ['47.75.33.177:9092','47.75.176.97:9092','47.75.170.254:9092']
#        HOST: 47.75.116.175:9092
#        topic: notice-test
#        topic: notice-prod

DATADB:
    MYSQL:
        HOST:
        UNAME:
        PWD:
        DNAME:

INTERVAL:
    # 调度间隔时间（小时）
    TIME: 2
    # 请求间隔时间（秒）
    SLEEP: 2

DATADBO:
    MYSQL:
        HOST: 47.98.56.206
        UNAME: root
        PWD: 123456
        DNAME: llf